### PR TITLE
ci: test that setup-fpm passes all the fpm tests

### LINKED ISSUE #9: Have Action Verify Installed fpm Works
I think it would be desirable for this action to test that the fpm executable is also capable of building a simple project before completing. I recently had a situation where the CI environment changed such that the fpm executable no longer worked. See https://github.com/fortran-lang/fpm/issues/780 . If the action had reported that the fpm executable didn't work, it would have been easier to diagnose the underlying problem.

### PR DESCRIPTION
**Pull request by gnikit**
Fixes #9 

I thought it would be quite appropriate (and somewhat funny) to check that `fpm-setup` works by running the fpm test suite.

### CODE REVIEW

**Review by everythingfunctional — APPROVED** [review]
I like it.

**Comment by gnikit** [comment]
@everythingfunctional we might want to enable the `fortran-setup` only for macos where things are failing without it, because Linux and Windows are super slow to install also I get warning for the Windows setup for the compiler+version not being recognised (which we should be getting). I suspect that this is a `fortran-setup` bug though.

**Comment by everythingfunctional** [comment]
@gnikit , depends how confident you are that things will continue to work on Linux and Windows without it.

**Comment by gnikit** [comment]
> @gnikit , depends how confident you are that things will continue to work on Linux and Windows without it.

Good point, confidence level should be low. So I'll merge and we'll take the CI runtime hit for now, until I setup caching for the compilers in `setup-fortran`.

**Pull request merged**
